version: "3"
services:
 httpbin:
  image: kennethreitz/httpbin
  container_name: httpbin
  ports:
   - 8081:80
 anotherbackend:
  image: kennethreitz/httpbin
  container_name: anotherbackend
  ports:
   - 8082:80
 placeholder:
  image: svenwal/jsonplaceholder
  container_name: placeholder
  ports:
    - 3005:3000
 grafana:
  image: grafana/grafana
  container_name: grafana
  volumes:
    - ./cfg/grafana/:/etc/grafana/provisioning/
  ports:
   - 10100:3000
 prometheus:
  image: prom/prometheus
  container_name: prometheus
  hostname: prometheus
  volumes:
   - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
  command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
  ports:
   - 9090:9090
 syslog:
  image: pbertera/syslogserver
  container_name: syslog
  ports:
   - 10200:80
  environment:
   - SYSLOG_USERNAME=admin  
   - SYSLOG_PASSWORD=admin
 postgres:
  image: postgres
  restart: always
  container_name: postgres
  environment:
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
  ports:
   - 5432:5432
  # volumes:
  # - ./postgres-data:/var/lib/postgresql/data
 kong-ent-bootstrap:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3-alpine
  container_name: kong-ent-bootstrap
  hostname: kongBootstrap
  depends_on:
   - postgres
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - 'KONG_LICENSE_DATA='
   - KONG_PASSWORD=
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
 kong-ent:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:1.3-alpine
  container_name: kong-ent
  depends_on:
   - postgres
  restart: always
  ports:
   - 8000:8000
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8443:8443
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
  command: "kong start --run-migrations" #NOT PRODUCTION
  environment:
   #- KONG_ENFORCE_RBAC=on
   #- KONG_ADMIN_GUI_AUTH=basic-auth
   #- KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_PORTAL_GUI_HOST=localhost:8003
   - KONG_PORTAL_GUI_PROTOCOL=http
   - KONG_PORTAL=on
   #- KONG_PORTAL_AUTH=openid-connect
   #- KONG_PORTAL_AUTH=basic-auth
   - KONG_ADMIN_GUI_URL=http://localhost:8002
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_CASSANDRA_CONTACT_POINTS=cassandra
   - 'KONG_LICENSE_DATA='
   - KONG_VITALS=on
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
   - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
   - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
   - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
   - KONG_PORTAL_EMAILS_FROM=training@apim.eu
   - KONG_PORTAL_EMAILS_REPLY_TO=training@apim.eu
   - KONG_SMTP_MOCK=off
   - KONG_SMTP_HOST=mail.datental.de
   - KONG_SMTP_PORT=587
   - KONG_SMTP_AUTH_TYPE=plain
   - KONG_SMTP_STARTTLS=on
   - KONG_SMTP_USERNAME=training@apim.eu
   - KONG_SMTP_PASSWORD=
   - KONG_SMTP_ADMIN_EMAILS=training@apim.eu
   - KONG_VITALS_STRATEGY=database # or 'influxdb' or 'prometheus' or 'database'
   - KONG_VITALS_TSDB_ADDRESS=prometheus:9090
   - KONG_VITALS_STATSD_ADDRESS=statsd_exporter:9125
